export const json_ride = {
  ride_id: 1,
  passenger_user_id: 1,
  passenger_name: "Heber Stein Mazutti",
  passenger_phone: "(11) 99999-9999",
  pickup_address: "Av. Paulista, 1500 - Jardim Paulista",
  pickup_date: "2025-02-17",
  dropoff_address: "Shopping Morumbi",
  status: "A",
  driver_user_id: 2,
  driver_name: "João Martins",
  latitude: "-23.561747",
  longitude: "-46.656244",
};

export const json_rides = [
  {
    ride_id: 1,
    passenger_user_id: 1,
    passenger_name: "Testolino Peter",
    passenger_phone: "(11) 99999-9999",
    pickup_address:
      "Prefeitura de Mogi das Cruzes - Centro, Mogi das Cruzes - SP",
    pickup_date: "2025-02-16",
    dropoff_address: "Parque Centenário - Mogilar, Mogi das Cruzes - SP",
    status: "P",
    driver_user_id: 2,
    driver_name: "João Martins",
    latitude: "-23.5195881",
    longitude: "-46.1868221",
  },
  {
    ride_id: 2,
    passenger_user_id: 3,
    passenger_name: "João da Silva",
    passenger_phone: "(11) 99999-9999",
    pickup_address: "Av. Ipiranga, 123 - Centro",
    pickup_date: "2025-02-16",
    dropoff_address: "MASP",
    status: "A",
    driver_user_id: 4,
    driver_name: "Fernando Assis",
    latitude: "-23.561747",
    longitude: "-46.656244",
  },
  {
    ride_id: 3,
    passenger_user_id: 3,
    passenger_name: "Testerson de Souza",
    passenger_phone: "(11) 99999-9999",
    pickup_address: "R. Dr. Ricardo Vilela - Centro, Mogi das Cruzes - SP",
    pickup_date: "2025-02-17",
    dropoff_address:
      "Av. Dr. Cândido X. de Almeida e Souza, 200 - Centro Cívico, Mogi das Cruzes - SP",
    status: "P",
    driver_user_id: 4,
    driver_name: "Fernando Assis",
    latitude: "-23.5219234",
    longitude: "-46.1960252",
  },
];
